"""
ai_disclosure.py — what we tell people about the AI, and proof of what
they agreed to.

TWO AUDIENCES, TWO DOCUMENTS.

The PRACTITIONER is buying a system that acts on their business. They
need to know what it decides on its own, what it never decides, and
where the record of it lives.

Their CLIENTS never signed up for anything. They may be texting a salon
or filling in a form on a website, and something answers. Telling them
that is not a legal formality, it is the difference between a tool and a
deception — and it has to be short enough to actually be read.

WHY THE TEXT IS HASHED.

A consent record that stores a version NUMBER proves nothing. Version 1
is whatever the file says version 1 is today, and files change. Storing
the SHA-256 of the exact bytes someone accepted makes the claim
checkable years later: re-hash the archived text and compare. If the
text was edited after the fact, the hashes diverge and the record says
so instead of quietly agreeing with the new wording.

That is the same reason the action ledger hashes its rows. A promise you
can silently rewrite is not evidence.

VERSIONS ARE APPEND-ONLY IN SPIRIT: to change what people agreed to, add
a version. Never edit one that has been shown to anyone — a test pins
the hash of every historical version for exactly that reason.
"""
from __future__ import annotations

import hashlib
from typing import Dict, List, Optional

# ── The practitioner-facing disclosure ────────────────────────────────
PRACTITIONER_V1 = """\
How AI works in the Solutionist System

Chief is an AI assistant. It reads your business data to answer you, and
it can take actions on your behalf.

WHAT IT DOES ON ITS OWN
Chief drafts, summarises, and prepares work without asking. It can send
routine follow-ups and reminders where you have switched that on.

WHAT IT NEVER DOES ON ITS OWN
It does not contact your clients on its own if your business is in a
regulated field and you have not enabled that. It does not act on
anything that affects many records at once without you confirming the
list on screen. It does not delete a client record that still has
history attached to it.

WHAT IS WRITTEN DOWN
Every action Chief takes is recorded in an append-only ledger with the
model that made the decision, whether it succeeded, and what authorised
it. You can read it, and so can an auditor you invite. The record cannot
be edited, including by us.

WHAT YOU CAN TURN OFF
Client-facing autonomy, scheduled sweeps, and AI voice are all yours to
disable. Turning them off never stops you doing the same work yourself.

AI GETS THINGS WRONG
Chief can be confidently wrong. Anything that leaves your business —
an email, a text, an invoice, a document — is yours to check. The ledger
records what was sent; it does not make it correct.
"""

# ── The client-facing disclosure ──────────────────────────────────────
# Deliberately short. This is read on a phone, mid-conversation, by
# somebody who did not come here to read a policy.
CLIENT_V1 = """\
You're talking to an AI assistant

Replies here are generated by an AI working for this business, not by a
person. It can book, answer questions, and pass things on.

It can be wrong. For anything that matters — money, health, a deadline —
ask for a human, and you will get one.

Your messages are stored by the business you're contacting. Reply STOP
to any text to stop receiving them.
"""

# ── The client-facing disclosure, in one line, for SMS ────────────────
# A text message is not a web page. CLIENT_V1 is already short for a
# policy and is still four paragraphs, which on SMS means several paid
# segments stapled to somebody's appointment reminder — and a notice
# that annoying is one practitioners will ask to turn off.
#
# So this says the one thing that cannot be left out: that the thing
# replying is not a person, and that a person is available. Everything
# else in CLIENT_V1 (storage, STOP) is either already in the message
# tail or belongs in a conversation nobody is having by text.
#
# It is a SEPARATE VERSIONED DOCUMENT rather than a slice of CLIENT_V1
# because it is separately shown, and a record of what somebody was
# told has to hash the words they actually saw.
#
# EVERY CHARACTER HERE IS GSM-7. This is not stylistic. A single
# character outside that alphabet — an em dash, a curly apostrophe, an
# ellipsis — forces the entire message into UCS-2, and a UCS-2 segment
# holds 70 characters instead of 160. One typographic dash would more
# than double the segment count, and the cost, of every message this
# notice rides on. The first draft of this line had one.
CLIENT_SMS_V1 = "Replies here are AI-generated. Ask for a human any time."

_DOCUMENTS: Dict[str, Dict[str, str]] = {
    "practitioner": {"1": PRACTITIONER_V1},
    "client": {"1": CLIENT_V1},
    "client_sms": {"1": CLIENT_SMS_V1},
}

CURRENT: Dict[str, str] = {"practitioner": "1", "client": "1",
                           "client_sms": "1"}


def text_hash(text: str) -> str:
    """SHA-256 of the exact bytes. Normalised only for line endings,
    because a file checked out on Windows must hash the same as the one
    the record was written from — otherwise every consent looks tampered
    with on the wrong machine."""
    return hashlib.sha256(
        text.replace("\r\n", "\n").encode("utf-8")).hexdigest()


def audiences() -> List[str]:
    return sorted(_DOCUMENTS)


def get(audience: str, version: Optional[str] = None) -> Optional[Dict[str, str]]:
    """One disclosure document, with the hash a consent record stores."""
    docs = _DOCUMENTS.get(audience)
    if not docs:
        return None
    v = str(version or CURRENT.get(audience) or "")
    body = docs.get(v)
    if body is None:
        return None
    return {"audience": audience, "version": v, "text": body,
            "hash": text_hash(body)}


def current(audience: str) -> Optional[Dict[str, str]]:
    return get(audience, CURRENT.get(audience))


def is_current(audience: str, version: Optional[str],
               accepted_hash: Optional[str] = None) -> bool:
    """Whether an acceptance still stands.

    A version match is NOT enough on its own. If a hash was recorded and
    no longer matches the text we ship, the document changed underneath
    the person who agreed to it — and that acceptance is stale even
    though the number is right. Returning True there would be the whole
    failure this module exists to prevent.
    """
    cur = current(audience)
    if not cur or str(version or "") != cur["version"]:
        return False
    if accepted_hash and accepted_hash != cur["hash"]:
        return False
    return True
