"""
lead_attribution.py — where the lead actually came from.

THE DEFECT
═══════════════════════════════════════════════════════════════════════
WebsiteTraffic.tsx:188 computes a form's top traffic source as

    ev.data?.utm_source || ev.data?.referrer_host || ev.data?.referrer
                                                  || 'direct'

and nothing in either repo writes any of the three. Every form on the
funnel has therefore reported "direct" since the day that line was
written — a UI stating a fact it has no way to know, which is worse
than a blank.

WHY THIS READS THE REFERER HEADER INSTEAD OF ASKING THE CLIENT
═══════════════════════════════════════════════════════════════════════
The obvious design has each form post its own `utm_source` and
`document.referrer`. But the contact form is emitted from at least four
renderers — site_modules/contact_footer, studio_layouts/movement,
studio_layouts/sections/contact, and whatever the builder's LLM writes
for a bespoke site — plus the intake embed, the concierge widget and
the booking widget. Some of those are generated by a model and cannot
be made to cooperate at all. A design that needs every client updated
is a design that is partially deployed forever, and half-attributed
data is worse than none: it looks complete.

The browser already tells us, for free, on every one of those posts.
`Referer` is the page the form was sitting on — which gives the landing
path AND that page's own query string, where the campaign parameters
live. Zero client changes, works on sites nobody has redeployed, works
on sites a model wrote.

The one thing a header cannot give is `document.referrer`, the site
they came FROM. Clients that choose to send it get that too; clients
that do not still get campaign and landing page. Better everywhere,
required nowhere.

PRIVACY
═══════════════════════════════════════════════════════════════════════
Referrers are reduced to a HOST before storage. site_analytics.py
already states the reason and this follows it: "Full referrer URLs leak
search terms."

Query strings are dropped except an explicit whitelist of campaign
keys. A query string on somebody else's page can contain anything —
an email address, a session token, a password reset link — and none of
that belongs in a contacts row because a marketing report wanted to
know about Google Ads.
"""
from __future__ import annotations

import logging
from datetime import datetime, timezone
from typing import Any, Dict, Optional
from urllib.parse import parse_qsl, urlparse

logger = logging.getLogger("lead_attribution")

# The ONLY query keys ever read off a referring URL. Everything else on
# that page's query string is dropped unread.
CAMPAIGN_KEYS = (
    "utm_source", "utm_medium", "utm_campaign", "utm_term", "utm_content",
    "gclid", "fbclid", "ref",
)

MAX_VALUE = 120
MAX_PATH = 200

# Same three classes site_analytics already buckets into, so the two
# datasets can eventually be compared without a translation table.
_MOBILE = ("iphone", "android", "ipod", "windows phone", "mobile")
_TABLET = ("ipad", "tablet", "kindle", "silk", "playbook")


def _clip(value: Any, limit: int = MAX_VALUE) -> Optional[str]:
    text = str(value or "").strip()
    return text[:limit] or None


def _host(url: Any) -> Optional[str]:
    """Host only. Never the path, never the query."""
    try:
        host = (urlparse(str(url or "")).hostname or "").strip().lower()
    except (ValueError, TypeError):
        return None
    return host[:MAX_VALUE] or None


def _device(user_agent: str) -> Optional[str]:
    ua = (user_agent or "").lower()
    if not ua:
        return None
    if any(t in ua for t in _TABLET):
        return "tablet"
    if any(m in ua for m in _MOBILE):
        return "mobile"
    return "desktop"


def _campaign_from_query(query: str) -> Dict[str, str]:
    out: Dict[str, str] = {}
    if not query:
        return out
    try:
        pairs = parse_qsl(query, keep_blank_values=False)
    except (ValueError, TypeError):
        return out
    for key, value in pairs:
        k = key.strip().lower()
        if k in CAMPAIGN_KEYS:
            clipped = _clip(value)
            if clipped:
                out[k] = clipped
    return out


def capture(request: Any = None, body: Optional[Dict[str, Any]] = None,
            *, source_detail: Optional[str] = None,
            submission: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    """Build the attribution blob for one submission. Never raises.

    `request` is the FastAPI/Starlette request the form posted to; its
    Referer header is the page the form was on. `body` may carry an
    optional `attribution` object from a client that chose to send
    `document.referrer` — the one signal a header cannot supply.

    Returns {} when there is genuinely nothing to record, so a caller
    can store null rather than an object full of nulls that reads like
    a failed lookup.
    """
    out: Dict[str, Any] = {}
    try:
        headers = getattr(request, "headers", None) or {}

        referer = headers.get("referer") or headers.get("referrer") or ""
        if referer:
            try:
                parsed = urlparse(referer)
                out.update(_campaign_from_query(parsed.query))
                host = (parsed.hostname or "").strip().lower()
                if host:
                    out["landing_host"] = host[:MAX_VALUE]
                path = (parsed.path or "").strip()
                if path:
                    # Path WITHOUT the query. The whitelist above already
                    # took what was wanted from it.
                    out["landing_path"] = path[:MAX_PATH]
            except (ValueError, TypeError):
                pass

        device = _device(headers.get("user-agent") or "")
        if device:
            out["device"] = device

        # Client-supplied extras. Explicitly NOT trusted for anything
        # security-relevant — this is a marketing report, and the worst
        # a lie here can do is misattribute one row.
        client = (body or {}).get("attribution")
        if isinstance(client, dict):
            for key in CAMPAIGN_KEYS:
                if key not in out:
                    value = _clip(client.get(key))
                    if value:
                        out[key] = value
            # The site they came FROM, as a host. This is the piece the
            # Referer header cannot give us.
            ref_host = _host(client.get("referrer")) or _clip(
                client.get("referrer_host"))
            if ref_host and ref_host != out.get("landing_host"):
                out["referrer_host"] = ref_host
            page = _clip(client.get("landing_path"), MAX_PATH)
            if page and "landing_path" not in out:
                out["landing_path"] = page.split("?")[0].split("#")[0]

        if source_detail:
            out["source_detail"] = _clip(source_detail, MAX_PATH)

        # What they SAID sent them. Kept beside the measured signals
        # rather than instead of them: "Friend" and utm_source=google
        # are both true when somebody googles a name a friend gave them.
        said = self_reported_source(submission)
        if said:
            out["self_reported"] = said

        if out:
            out["captured_at"] = (datetime.now(timezone.utc).isoformat()
                                  .replace("+00:00", "Z"))
    except Exception as e:                       # never break a capture
        logger.warning("[lead_attribution] capture failed: %s", e)
        return {}
    return out


def from_client(payload: Optional[Dict[str, Any]]) -> Dict[str, Any]:
    """Sanitize an attribution blob the app sends directly. Never raises.

    Signup and the waitlist live on the app domain, where there is no
    marketing-page Referer to read — the app captured the campaign params
    off its own front-door URL and stashed them (same stash-and-redeem
    pattern as invite tokens, because the email-confirmation link returns
    to the bare origin). Same whitelist and clipping as capture(): a
    client-supplied blob is a marketing report, not an identity claim.
    """
    out: Dict[str, Any] = {}
    try:
        if not isinstance(payload, dict):
            return out
        for key in CAMPAIGN_KEYS:
            value = _clip(payload.get(key))
            if value:
                out[key] = value
        ref_host = _host(payload.get("referrer")) or _clip(payload.get("referrer_host"))
        if ref_host:
            out["referrer_host"] = ref_host
        page = _clip(payload.get("landing_path"), MAX_PATH)
        if page:
            out["landing_path"] = page.split("?")[0].split("#")[0]
        if out:
            out["captured_at"] = (datetime.now(timezone.utc).isoformat()
                                  .replace("+00:00", "Z"))
    except Exception as e:                       # never break a capture
        logger.warning("[lead_attribution] from_client failed: %s", e)
        return {}
    return out


# Self-reported attribution. The form templates have shipped a "How did
# you hear about us?" select since the beginning — Friend / Social Media
# / Google / Drive-by / Event / Other — and NOTHING has ever read it. It
# sat in metadata.submission where no report, no prompt and no analytics
# surface looked at it.
#
# It is worth reading precisely because it answers what the Referer
# header cannot: a walk-in, a word-of-mouth referral, a flyer, a van
# with a phone number on it. Half of a small business's marketing leaves
# no digital trace at all, and the visitor is the only witness.
SELF_REPORT_KEYS = ("how_heard", "how_did_you_hear", "how_did_you_hear_about_us",
                    "heard_about_us", "referral_source", "how_found_us",
                    "where_did_you_hear")


def self_reported_source(submission: Optional[Dict[str, Any]]) -> Optional[str]:
    """What they SAID sent them, if the form asked. Free text and select
    values both — a select is the common case, but a practitioner who
    made it a text box gets the same treatment."""
    for key, value in (submission or {}).items():
        if str(key).strip().lower() in SELF_REPORT_KEYS:
            text = _clip(value, MAX_VALUE)
            # "Other" and the unselected placeholder say nothing.
            if text and text.strip().lower() not in ("other", "n/a", "none",
                                                     "select...", "-"):
                return text
    return None


def event_fields(attribution: Optional[Dict[str, Any]]) -> Dict[str, Any]:
    """The subset the funnel reads off an event's `data`.

    WebsiteTraffic.tsx looks for exactly `utm_source`, `referrer_host`
    and `referrer`, in that order. Those key names are the contract;
    renaming them here silently returns the funnel to reporting
    'direct' for everything.
    """
    a = attribution or {}
    fields: Dict[str, Any] = {}
    for key in ("utm_source", "utm_medium", "utm_campaign",
                "referrer_host", "landing_path", "device", "self_reported"):
        if a.get(key):
            fields[key] = a[key]
    return fields


def detail_for(attribution: Optional[Dict[str, Any]],
               fallback: Optional[str] = None) -> Optional[str]:
    """What to write into contacts.source_detail.

    An explicit label (an intake form's name) wins — it is what the
    funnel groups by and what the practitioner recognises. Otherwise
    the landing page, which at least says which page of their site the
    person was reading when they decided to get in touch.
    """
    a = attribution or {}
    return (_clip(a.get("source_detail"), MAX_PATH)
            or _clip(fallback, MAX_PATH)
            or _clip(a.get("landing_path"), MAX_PATH))
