"""Trusted, deterministic HyperFrames compiler for the saved scene schema.

No arbitrary CSS, scripts, HTML, URLs or file paths cross the model boundary.
All media paths are generated by the worker after tenant authorization.
"""
from pathlib import Path
from html import escape
import json
import shutil
from video_studio_models import Composition

RUNTIME=Path(__file__).parent/'video_worker'
def compile_project(spec:Composition,folder:Path,media:dict,voices:dict):
    folder.mkdir(exist_ok=True,parents=True);(folder/'assets').mkdir(exist_ok=True)
    shutil.copy2(RUNTIME/'compiler_assets/gsap.min.js',folder/'assets/gsap.min.js')
    fonts=RUNTIME/'compiler_assets'
    for weight in (400,600,700):shutil.copy2(fonts/f'font-{weight}.woff2',folder/f'assets/font-{weight}.woff2')
    w,h={'landscape':(1920,1080),'portrait':(1080,1920),'square':(1080,1080)}[spec.format]
    palette={'midnight':('#080F1D','#F7F9FF','#ADC2DA'), 'paper':('#F3F0E9','#172538','#45556B'),'warm':('#251E24','#FFF4E9','#D8BBAB')}[spec.theme]
    bg,fg,muted=palette
    # A separate fixed stage means the same native typography stays readable at every size.
    portrait=spec.format=='portrait';landscape=spec.format=='landscape'
    headline=106 if landscape else 86
    css=''.join(f"@font-face{{font-family:'Video Sans';src:url('assets/font-{x}.woff2');font-weight:{x};font-display:block}}" for x in (400,600,700))
    css+=f'''*{{box-sizing:border-box}}html,body{{margin:0;width:{w}px;height:{h}px;overflow:hidden;background:{bg}}}
    #root{{position:relative;width:{w}px;height:{h}px;overflow:hidden;color:{fg};font-family:'Video Sans',Arial,sans-serif}}
    .scene{{position:absolute;inset:0;padding:{100 if landscape else 80}px;background:{bg};overflow:hidden}}
    .ambient{{position:absolute;inset:0;background:radial-gradient(ellipse at 80% 20%,{spec.accent}22,transparent 65%);pointer-events:none}}
    .copy{{position:absolute;left:8%;top:{'15%' if portrait else '24%'};width:84%;z-index:2}}
    .eyebrow{{font-size:24px;font-weight:600;letter-spacing:5px;color:{muted};margin-bottom:32px}}
    h1{{font-size:{headline}px;line-height:1.08;letter-spacing:-4px;font-weight:700;margin:0;white-space:pre-line;overflow-wrap:anywhere}}
    .subtitle{{font-size:{36 if landscape else 32}px;line-height:1.5;color:{muted};margin-top:35px;max-width:1150px;white-space:pre-line}}
    .rule{{width:145px;height:5px;background:{spec.accent};margin-bottom:38px;transform-origin:left}}
    .media{{position:absolute;left:8%;top:12%;width:84%;height:68%;border-radius:26px;overflow:hidden;background:#000}}
    .media img,.media video{{width:100%;height:100%;object-fit:contain}}
    .split .copy{{width:{'84%' if portrait else '40%'};top:{'10%' if portrait else '23%'}}}
    .split .media{{left:{'8%' if portrait else '54%'};top:{'49%' if portrait else '17%'};width:{'84%' if portrait else '39%'};height:{'37%' if portrait else '64%'}}}
    .split h1{{font-size:{82 if landscape else 74}px}}
    .image .copy{{top:80%;width:84%}}.image h1{{font-size:48px;letter-spacing:-1px}}.image .eyebrow,.image .rule,.image .subtitle{{display:none}}
    .quote h1{{font-size:{88 if landscape else 72}px}}.quote .copy{{width:82%}}
    .points{{display:flex;flex-direction:{'row' if landscape else 'column'};gap:22px;margin-top:44px}}
    .point{{flex:1;border:1px solid {muted}44;background:{spec.accent}0b;border-radius:18px;padding:30px;font-size:30px;line-height:1.4}}
    .features .copy{{top:{'12%' if portrait else '19%'}}}.features h1{{font-size:{88 if landscape else 70}px}}
    .statistic{{font-size:{180 if landscape else 160}px;line-height:1;font-weight:700;color:{spec.accent};letter-spacing:-8px;margin-bottom:35px}}
    .stat h1{{font-size:60px;letter-spacing:-2px}}.closing .subtitle{{display:inline-block;padding:22px 30px;border:1px solid {spec.accent};border-radius:12px;color:{fg}}}
    .caption{{position:absolute;left:8%;right:8%;bottom:5%;text-align:center;z-index:50;font-size:30px;line-height:1.4;color:#fff}}
    .caption span{{background:#070C17E8;padding:12px 20px;box-decoration-break:clone;-webkit-box-decoration-break:clone;border-radius:7px}}
    .scene-count{{position:absolute;right:8%;bottom:3%;font-size:17px;color:{muted};letter-spacing:3px}}
    '''
    parts=[]; animations=[];audio=[];total=0
    for i,scene in enumerate(spec.scenes):
        sid=f'scene-{i}';start=total;total+=scene.seconds
        art=''
        if scene.asset_id:
            item=media[str(scene.asset_id)];src=escape(item['path'],quote=True)
            if item['mime_type'].startswith('video/'):
                art=f'<video id="video-{i}" class="clip" data-start="{start}" data-duration="{scene.seconds}" data-media-start="{scene.source_start}" src="{src}" muted playsinline style="object-fit:{scene.fit}"></video>'
                # Source audio is deliberately muted in the composed video. User can supply a soundtrack separately.
            else: art=f'<img id="image-{i}" class="clip" data-start="{start}" data-duration="{scene.seconds}" src="{src}" alt="" style="object-fit:{scene.fit}">'
            art=f'<div class="media">{art}</div>'
        points='<div class="points">'+''.join(f'<div class="point">{escape(t)}</div>' for t in scene.points)+'</div>' if scene.points else ''
        stat=f'<div class="statistic"><span id="counter-{i}">0</span>{escape(scene.suffix)}</div>' if scene.layout=='stat' else ''
        parts.append(f'''<section id="{sid}" class="clip scene {scene.layout}" data-start="{start}" data-duration="{scene.seconds}"><div class="ambient" data-layout-ignore></div>{art}<div class="copy"><div class="rule"></div><div class="eyebrow">{escape(scene.eyebrow)}</div>{stat}<h1>{escape(scene.title)}</h1><div class="subtitle">{escape(scene.subtitle)}</div>{points}</div><div class="scene-count">{i+1:02d} / {len(spec.scenes):02d}</div></section>''')
        prefix=f'#{sid}'
        if scene.motion!='still': animations.append(f"tl.fromTo('{prefix} .copy',{{opacity:0,y:26}},{{opacity:1,y:0,duration:.75,ease:'power3.out'}},{start+.15});")
        if scene.motion!='still': animations.append(f"tl.fromTo('{prefix} .rule',{{scaleX:0}},{{scaleX:1,duration:.9,ease:'power2.out'}},{start+.25});")
        if art:
            if scene.motion!='still': animations.append(f"tl.fromTo('{prefix} .media',{{opacity:0,y:20}},{{opacity:1,y:0,duration:.8,ease:'power3.out'}},{start+.1});")
            if scene.motion=='push': animations.append(f"tl.fromTo('{prefix} .media img,{prefix} .media video',{{scale:1}},{{scale:1.06,duration:{scene.seconds},ease:'none'}},{start});")
            if scene.motion=='pan': animations.append(f"tl.fromTo('{prefix} .media',{{x:-12}},{{x:12,duration:{scene.seconds},ease:'sine.inOut'}},{start});")
        if points and scene.motion!='still': animations.append(f"tl.fromTo('{prefix} .point',{{opacity:0,y:20}},{{opacity:1,y:0,duration:.6,stagger:.18}},{start+.8});")
        if scene.layout=='stat':
            animations.append(f"const c{i}={{v:0}};tl.to(c{i},{{v:{scene.statistic},duration:1.6,ease:'power2.out',onUpdate:()=>{{document.querySelector('#counter-{i}').textContent=Math.round(c{i}.v).toLocaleString('en-US')}}}},{start+.3});")
        animations.append(f"tl.to('{prefix} .copy',{{opacity:0,y:-8,duration:.22}},{total-.25});")
        animations.append(f"tl.set('{prefix} .copy',{{opacity:0}},{total});")
        voice=voices.get(scene.id)
        if voice:
            audio.append(f'<audio id="voice-{i}" src="{escape(voice["path"])}" data-start="{start+.25}" data-duration="{voice["duration"]}" data-volume=".8"></audio>')
        if spec.captions and scene.narration and voice:
            words=scene.narration.split();chunks=[' '.join(words[j:j+9]) for j in range(0,len(words),9)]
            for j,chunk in enumerate(chunks):
                at=start+.25+voice['duration']*j/len(chunks);dur=voice['duration']/len(chunks)
                parts.append(f'<div id="caption-{i}-{j}" class="clip caption" data-start="{at}" data-duration="{dur}" data-track-index="20"><span>{escape(chunk)}</span></div>')
    if spec.music_asset_id:
        music=media[str(spec.music_asset_id)];duration=min(total,music.get('duration_seconds') or total)
        audio.append(f'<audio id="music" src="{escape(music["path"])}" data-start="0" data-duration="{duration}" data-volume=".12"></audio>')
    html=f'''<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><title>{escape(spec.title)}</title><script src="assets/gsap.min.js"></script><style>{css}</style></head><body><div id="root" data-composition-id="main" data-start="0" data-duration="{total}" data-width="{w}" data-height="{h}">{''.join(parts)}{''.join(audio)}</div><script>window.__timelines=window.__timelines||{{}};const tl=gsap.timeline({{paused:true}});{''.join(animations)}window.__timelines.main=tl;</script></body></html>'''
    (folder/'index.html').write_text(html,encoding='utf-8')
    (folder/'hyperframes.json').write_text(json.dumps({'authoringSkill':'general-video'}))
    return total
