"""Trusted, deterministic HyperFrames compiler for the saved scene schema.

No arbitrary CSS, scripts, HTML, URLs or file paths cross the model boundary.
All media paths are generated by the worker after tenant authorization.

Quality pass 2026-09-08: every scene is composed like a broadcast piece
rather than a slide. Photos never sit in a black letterbox (a blurred copy
of the picture fills the frame behind a contained image), scenes crossfade
instead of hard-cutting, headlines land line by line, images move with a
slow Ken Burns push, a thin accent progress line runs under the whole
piece, captions are timed to the spoken phrase when the narrator returns
word timings, and the paper/warm themes set headlines in a serif display
face so the three themes read as three different films.
"""
from pathlib import Path
from html import escape
import json
import re
import shutil
from video_studio_models import Composition

RUNTIME=Path(__file__).parent/'video_worker'
CROSSFADE=.6
GRAIN="url(\"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='200' height='200'><filter id='n'><feTurbulence type='fractalNoise' baseFrequency='.9' numOctaves='2' stitchTiles='stitch'/></filter><rect width='200' height='200' filter='url(%23n)' opacity='.55'/></svg>\")"
THEMES={
    # bg, fg, muted, secondary glow, headline family
    'midnight':('#080F1D','#F7F9FF','#ADC2DA','#1B3A6B','sans'),
    'paper':('#F3F0E9','#172538','#45556B','#E4DCCB','serif'),
    'warm':('#251E24','#FFF4E9','#D8BBAB','#5A2E2C','serif'),
}

def lines(text):
    return ''.join(f'<span class="line"><span class="line-in">{escape(part) or "&nbsp;"}</span></span>' for part in text.split('\n'))

def caption_phrases(scene,voice,start):
    """Timed caption phrases. Word timings from the narrator win; otherwise
    the narration is split evenly so captions still follow the voice."""
    timed=voice.get('phrases')
    if timed:
        return [(text,start+.25+a,max(.6,b-a)) for text,a,b in timed]
    words=scene.narration.split();chunks=[' '.join(words[j:j+7]) for j in range(0,len(words),7)]
    return [(chunk,start+.25+voice['duration']*j/len(chunks),voice['duration']/len(chunks)) for j,chunk in enumerate(chunks)]

def compile_project(spec:Composition,folder:Path,media:dict,voices:dict,music:dict|None=None):
    folder.mkdir(exist_ok=True,parents=True);(folder/'assets').mkdir(exist_ok=True)
    shutil.copy2(RUNTIME/'compiler_assets/gsap.min.js',folder/'assets/gsap.min.js')
    fonts=RUNTIME/'compiler_assets'
    for weight in (400,600,700):shutil.copy2(fonts/f'font-{weight}.woff2',folder/f'assets/font-{weight}.woff2')
    shutil.copy2(fonts/'display.woff2',folder/'assets/display.woff2')
    w,h={'landscape':(1920,1080),'portrait':(1080,1920),'square':(1080,1080)}[spec.format]
    bg,fg,muted,glow,family=THEMES[spec.theme]
    accent=spec.accent
    portrait=spec.format=='portrait';landscape=spec.format=='landscape'
    pad=120 if landscape else 72
    headline=112 if landscape else 92
    display="'Video Display',Georgia,serif" if family=='serif' else "'Video Sans',Arial,sans-serif"
    tracking='-2px' if family=='serif' else '-4px'
    css=''.join(f"@font-face{{font-family:'Video Sans';src:url('assets/font-{x}.woff2');font-weight:{x};font-display:block}}" for x in (400,600,700))
    css+="@font-face{font-family:'Video Display';src:url('assets/display.woff2');font-weight:600 700;font-display:block}"
    css+=f'''*{{box-sizing:border-box}}html,body{{margin:0;width:{w}px;height:{h}px;overflow:hidden;background:{bg}}}
    #root{{position:relative;width:{w}px;height:{h}px;overflow:hidden;color:{fg};font-family:'Video Sans',Arial,sans-serif}}
    .scene{{position:absolute;inset:0;padding:{pad}px;background:{bg};overflow:hidden;opacity:0;display:flex;flex-direction:column;justify-content:center}}
    .ambient{{position:absolute;inset:0;pointer-events:none;background:radial-gradient(ellipse 70% 60% at 82% 18%,{accent}33,transparent 70%),radial-gradient(ellipse 60% 50% at 10% 92%,{glow}99,transparent 70%)}}
    .vignette{{position:absolute;inset:0;pointer-events:none;background:radial-gradient(ellipse 90% 90% at 50% 50%,transparent 55%,{bg}CC 100%)}}
    .grain{{position:absolute;inset:-50%;width:200%;height:200%;pointer-events:none;opacity:.045;background-image:{GRAIN};mix-blend-mode:overlay}}
    .copy{{position:relative;z-index:2;max-width:{1180 if landscape else 940}px}}
    .eyebrow{{font-size:{24 if landscape else 26}px;font-weight:600;letter-spacing:6px;text-transform:uppercase;color:{accent};margin-bottom:28px}}
    .eyebrow:empty{{display:none}}
    h1{{font-family:{display};font-size:{headline}px;line-height:1.04;letter-spacing:{tracking};font-weight:700;margin:0;overflow-wrap:anywhere}}
    .line{{display:block;overflow:hidden;padding:.04em 0 .08em}}.line-in{{display:block}}
    .subtitle{{font-size:{38 if landscape else 36}px;line-height:1.45;color:{muted};margin-top:34px;max-width:{960 if landscape else 900}px;white-space:pre-line}}
    .subtitle:empty{{display:none}}
    .rule{{width:120px;height:6px;border-radius:3px;background:{accent};margin-bottom:34px;transform-origin:left}}
    .media{{position:absolute;overflow:hidden;background:{glow};z-index:1}}
    .media .backdrop{{position:absolute;inset:-12%;width:124%;height:124%;object-fit:cover;filter:blur(46px) saturate(1.25);opacity:.8}}
    .media .shade{{position:absolute;inset:0;background:linear-gradient(180deg,{bg}00 0%,{bg}00 55%,{bg}66 100%)}}
    .media img.clip,.media video.clip{{position:absolute;inset:0;width:100%;height:100%;object-fit:contain;transform-origin:center}}
    .split .media{{left:{'8%' if portrait else '54%'};top:{'7%' if portrait else '10%'};width:{'84%' if portrait else '40%'};height:{'44%' if portrait else '80%'};border-radius:28px;box-shadow:0 40px 90px -30px #00000088}}
    .split.scene{{justify-content:{'flex-end' if portrait else 'center'}}}
    .split .copy{{width:{'100%' if portrait else '44%'}}}.split h1{{font-size:{84 if landscape else 78}px}}
    .image .media{{inset:0;border-radius:0}}.image .media .shade{{background:linear-gradient(180deg,{bg}00 35%,{bg}D9 100%)}}
    .image.scene{{justify-content:flex-end}}.image h1{{font-size:{64 if landscape else 66}px;letter-spacing:-2px}}
    .image .eyebrow,.image .rule{{display:none}}.image .subtitle{{margin-top:16px;color:{fg};opacity:.85}}
    .title h1{{font-size:{136 if landscape else 104}px}}.title .copy{{max-width:{1440 if landscape else 940}px}}
    .quote h1{{font-size:{92 if landscape else 76}px;font-weight:600;font-style:{'italic' if family=='serif' else 'normal'}}}.quote .copy{{max-width:{1380 if landscape else 940}px}}
    .quote .rule{{display:none}}.quote .subtitle{{font-size:30px;letter-spacing:2px;text-transform:uppercase;color:{accent}}}
    .points{{display:flex;flex-direction:{'row' if landscape else 'column'};gap:22px;margin-top:48px}}
    .point{{flex:1;border-left:5px solid {accent};background:{fg}0D;border-radius:0 20px 20px 0;padding:30px 32px;font-size:{32 if landscape else 34}px;line-height:1.35;font-weight:600}}
    .features h1{{font-size:{92 if landscape else 76}px}}
    .statistic{{font-family:{display};font-size:{210 if landscape else 170}px;line-height:1;font-weight:700;color:{accent};letter-spacing:-8px;margin-bottom:26px}}
    .stat h1{{font-size:{66 if landscape else 62}px;letter-spacing:-2px}}.stat .rule{{display:none}}
    .closing.scene{{align-items:center;text-align:center}}.closing .rule{{margin:0 auto 34px}}.closing h1{{font-size:{104 if landscape else 88}px}}
    .closing .subtitle:empty{{display:none}}.closing .subtitle{{display:inline-block;margin-top:44px;padding:22px 40px;border-radius:999px;background:{accent};color:{'#0B1020' if spec.theme!='paper' else '#FFFFFF'};font-weight:600;font-size:{36 if landscape else 34}px}}
    .caption{{position:absolute;left:8%;right:8%;bottom:{'14%' if portrait else '7%'};text-align:center;z-index:50;font-size:{34 if landscape else 40}px;line-height:1.45;font-weight:600;color:#fff}}
    .caption span{{background:#0B1020E0;padding:10px 22px;box-decoration-break:clone;-webkit-box-decoration-break:clone;border-radius:10px}}
    .progress{{position:absolute;left:0;bottom:0;height:6px;width:100%;background:{accent};transform-origin:left;transform:scaleX(0);z-index:60;opacity:.9}}
    .logo.scene{{align-items:center;text-align:center}}
    .logo .media{{position:relative;width:{300 if landscape else 250}px;height:{300 if landscape else 250}px;background:transparent;overflow:visible;margin:0 auto 36px;z-index:2}}
    .logo .media .shade,.logo .media .backdrop{{display:none}}
    .logo .glow{{position:absolute;inset:-45%;border-radius:50%;background:radial-gradient(circle,{accent}77,transparent 62%);filter:blur(26px)}}
    .logo .ring{{position:absolute;inset:-16%;border-radius:50%;border:1px solid {fg}26}}
    .logo h1{{font-size:{100 if landscape else 80}px;letter-spacing:-3px}}.logo .rule{{display:none}}.logo .eyebrow{{margin-bottom:16px}}.logo .subtitle{{margin-top:20px}}
    .device{{border:1px solid {fg}22;box-shadow:0 70px 140px -50px #000000CC;background:{bg}}}.device .backdrop{{opacity:.5}}
    .device-glow{{position:absolute;left:{'8%' if portrait else '54%'};top:{'7%' if portrait else '10%'};width:{'84%' if portrait else '40%'};height:{'44%' if portrait else '80%'};border-radius:60px;background:radial-gradient(ellipse at 50% 55%,{accent}66,transparent 68%);filter:blur(60px);z-index:0}}
    .callout{{position:absolute;z-index:4;width:0;height:0}}
    .callout .cring{{position:absolute;left:-27px;top:-27px;width:54px;height:54px;border-radius:50%;border:3px solid {accent};box-shadow:0 0 0 9px {accent}33,0 0 30px {accent}88}}
    .callout .ctag{{position:absolute;left:44px;top:-22px;white-space:nowrap;background:{accent};color:#0B1020;font-weight:600;font-size:24px;padding:9px 16px;border-radius:10px;box-shadow:0 10px 30px #00000066}}
    .callout.flip .ctag{{left:auto;right:44px}}
    .demo .copy{{width:{'100%' if portrait else '42%'}}}.demo.scene{{justify-content:{'flex-end' if portrait else 'center'}}}.demo h1{{font-size:{84 if landscape else 72}px}}
    .app{{position:absolute;left:{'6%' if portrait else '50%'};top:{'8%' if portrait else '16%'};width:{'88%' if portrait else '46%'};height:auto;min-height:{'30%' if portrait else '36%'};max-height:{'47%' if portrait else '78%'};border-radius:22px;background:{'#0C1424' if spec.theme!='paper' else '#FFFFFF'};border:1px solid {fg}22;box-shadow:0 70px 140px -50px #000000CC;overflow:hidden;z-index:2;color:{fg}}}
    .app-glow{{position:absolute;left:{'6%' if portrait else '50%'};top:{'6%' if portrait else '11%'};width:{'88%' if portrait else '46%'};height:{'47%' if portrait else '78%'};border-radius:60px;background:radial-gradient(ellipse at 50% 55%,{accent}66,transparent 68%);filter:blur(60px);z-index:0}}
    .app-bar{{height:54px;display:flex;align-items:center;gap:9px;padding:0 22px;border-bottom:1px solid {fg}14;font-size:20px;color:{muted}}}.app-bar i{{width:12px;height:12px;border-radius:50%;background:{fg}33;display:inline-block}}.app-bar span{{margin-left:10px}}
    .app-body{{padding:32px 34px;display:flex;flex-direction:column;gap:20px}}
    .chat-head{{display:flex;align-items:center;gap:12px;font-size:22px;color:{muted}}}.chat-head b{{width:14px;height:14px;border-radius:50%;background:{accent};display:inline-block;box-shadow:0 0 16px {accent}}}
    .bubble{{max-width:88%;padding:18px 24px;border-radius:18px;font-size:27px;line-height:1.4}}
    .bubble.me{{align-self:flex-end;background:{accent};color:#0B1020;border-bottom-right-radius:6px}}.bubble.ai{{align-self:flex-start;background:{fg}12;border-bottom-left-radius:6px}}
    .ch{{opacity:0}}.caret{{display:inline-block;width:3px;height:1em;background:currentColor;vertical-align:-.15em;margin-left:2px}}
    .card{{align-self:stretch;border:1px solid {fg}1F;border-radius:16px;padding:22px 26px;display:flex;justify-content:space-between;align-items:center;gap:20px;background:{fg}08}}
    .card .ct{{font-size:25px;font-weight:600}}.card .cn{{font-size:20px;color:{muted};margin-top:6px}}.card .cv{{font-size:40px;font-weight:700;color:{accent};white-space:nowrap}}
    .chip{{display:inline-block;padding:6px 14px;border-radius:999px;background:#22C55E22;color:#22C55E;font-size:18px;font-weight:600;margin-top:10px}}
    .greet{{font-size:34px;font-weight:700}}.tiles{{display:grid;grid-template-columns:1fr 1fr;gap:16px}}
    .tile{{border:1px solid {fg}1F;border-radius:16px;padding:20px 22px;background:{fg}08}}.tile .tl{{font-size:17px;letter-spacing:2px;text-transform:uppercase;color:{muted}}}.tile .tv{{font-size:44px;font-weight:700;margin-top:6px}}
    .acts{{display:flex;flex-wrap:wrap;gap:10px}}.act{{padding:10px 16px;border-radius:12px;border:1px solid {fg}1F;font-size:20px;background:{fg}08}}
    '''
    parts=[]; animations=[];audio=[];total=0;count=len(spec.scenes)
    for i,scene in enumerate(spec.scenes):
        sid=f'scene-{i}';start=total;total+=scene.seconds;last=i==count-1
        # The outgoing scene keeps its picture up under the incoming crossfade.
        hold=0 if last else CROSSFADE
        art=''
        if scene.asset_id:
            item=media[str(scene.asset_id)];src=escape(item['path'],quote=True)
            if item['mime_type'].startswith('video/'):
                available=float(item.get('duration_seconds') or 0)-(scene.source_start+scene.seconds)
                tail=max(0,min(hold,available)) if item.get('duration_seconds') else 0
                art=f'<video id="video-{i}" class="clip" data-start="{start}" data-duration="{scene.seconds+tail}" data-media-start="{scene.source_start}" src="{src}" muted playsinline style="object-fit:{scene.fit}"></video>'
                # Source audio is deliberately muted in the composed video. User can supply a soundtrack separately.
                backdrop=''
            else:
                art=f'<img id="image-{i}" class="clip" data-start="{start}" data-duration="{scene.seconds+hold}" src="{src}" alt="" style="object-fit:{scene.fit}">'
                backdrop=f'<img class="backdrop" src="{src}" alt="">' if scene.fit=='contain' else ''
            callouts=''.join(f'<div class="callout{" flip" if c.x>58 else ""}" data-callout="{j}" style="left:{c.x}%;top:{c.y}%"><span class="cring"></span><span class="ctag">{escape(c.label)}</span></div>' for j,c in enumerate(scene.callouts))
            if scene.layout=='logo':
                art=f'<div class="media"><div class="glow"></div><div class="ring"></div>{art}</div>'
            else:
                device=scene.layout=='split' and scene.fit=='contain' and not item['mime_type'].startswith('video/')
                art=('<div class="device-glow" data-layout-ignore></div>' if device else '')+f'<div class="media{" device" if device else ""}">{backdrop}{art}<div class="shade"></div>{callouts}</div>'
        points='<div class="points">'+''.join(f'<div class="point">{escape(t)}</div>' for t in scene.points)+'</div>' if scene.points else ''
        stat=f'<div class="statistic"><span id="counter-{i}">0</span>{escape(scene.suffix)}</div>' if scene.layout=='stat' else ''
        if scene.layout=='demo' and scene.demo:
            d=scene.demo;bar=f'<div class="app-bar"><i></i><i></i><i></i><span>{escape(d.app_name)}</span></div>'
            if d.kind=='chat':
                typed=''.join(f'<span class="ch">{escape(ch) if ch!=" " else "&nbsp;"}</span>' for ch in d.prompt)
                card=f'<div class="card"><div><div class="ct">{escape(d.card_title)}</div><div class="cn">{escape(d.card_note)}</div><span class="chip">Ready</span></div><div class="cv">{escape(d.card_value)}</div></div>' if d.card_title else ''
                body=f'<div class="chat-head"><b></b>{escape(d.assistant)}</div><div class="bubble me">{typed}<span class="caret"></span></div><div class="bubble ai">{escape(d.reply)}</div>{card}'
            else:
                tiles=''.join(f'<div class="tile"><div class="tl">{escape(t.label)}</div><div class="tv">{escape(t.value)}</div></div>' for t in d.tiles)
                acts=('<div class="acts">'+''.join(f'<span class="act">{escape(a)}</span>' for a in d.actions)+'</div>') if d.actions else ''
                body=(f'<div class="greet">{escape(d.greeting)}</div>' if d.greeting else '')+f'<div class="tiles">{tiles}</div>{acts}'
            art=f'<div class="app-glow" data-layout-ignore></div><div class="app">{bar}<div class="app-body">{body}</div></div>'
        # Media owns its absolute clip time. Timing its parent as well makes
        # HyperFrames apply a second offset to source-video extraction.
        parts.append(f'''<section id="{sid}" class="scene {scene.layout}"><div class="ambient" data-layout-ignore></div>{art}<div class="vignette" data-layout-ignore></div><div class="copy"><div class="rule"></div><div class="eyebrow">{escape(scene.eyebrow)}</div>{stat}<h1>{lines(scene.title)}</h1><div class="subtitle">{escape(scene.subtitle)}</div>{points}</div></section>''')
        prefix=f'#{sid}'
        if i==0:animations.append(f"tl.set('{prefix}',{{opacity:1}},{start});")
        else:animations.append(f"tl.fromTo('{prefix}',{{opacity:0}},{{opacity:1,duration:{CROSSFADE},ease:'power2.inOut'}},{start});")
        animations.append(f"tl.set('{prefix}',{{opacity:0}},{total+hold});")
        moving=scene.motion!='still'
        if moving:
            animations.append(f"tl.fromTo('{prefix} .rule',{{scaleX:0}},{{scaleX:1,duration:.9,ease:'power3.out'}},{start+.2});")
            animations.append(f"tl.fromTo('{prefix} .eyebrow',{{opacity:0,y:14}},{{opacity:1,y:0,duration:.6,ease:'power2.out'}},{start+.25});")
            animations.append(f"tl.fromTo('{prefix} .line-in',{{yPercent:110}},{{yPercent:0,duration:.85,ease:'power4.out',stagger:.11}},{start+.3});")
            animations.append(f"tl.fromTo('{prefix} .subtitle',{{opacity:0,y:18}},{{opacity:1,y:0,duration:.7,ease:'power2.out'}},{start+.75});")
        if art:
            if moving:animations.append(f"tl.fromTo('{prefix} .media',{{opacity:0,scale:.97}},{{opacity:1,scale:1,duration:.9,ease:'power3.out'}},{start+.05});")
            span=scene.seconds+hold
            if scene.motion=='push':animations.append(f"tl.fromTo('{prefix} .media .clip',{{scale:1,yPercent:1.5}},{{scale:1.09,yPercent:-1.5,duration:{span},ease:'none'}},{start});")
            elif scene.motion=='pan':animations.append(f"tl.fromTo('{prefix} .media .clip',{{scale:1.12,xPercent:2.5}},{{scale:1.12,xPercent:-2.5,duration:{span},ease:'sine.inOut'}},{start});")
            elif scene.motion=='rise':animations.append(f"tl.fromTo('{prefix} .media .clip',{{scale:1.04}},{{scale:1,duration:{span},ease:'none'}},{start});")
        if scene.layout=='logo':
            animations.append(f"tl.fromTo('{prefix} .media',{{opacity:0,scale:.6}},{{opacity:1,scale:1,duration:1.1,ease:'back.out(1.6)'}},{start+.1});")
            animations.append(f"tl.fromTo('{prefix} .ring',{{scale:.5,opacity:0}},{{scale:1,opacity:1,duration:1.4,ease:'power3.out'}},{start+.3});")
            animations.append(f"tl.fromTo('{prefix} .glow',{{opacity:.4,scale:.8}},{{opacity:1,scale:1.15,duration:{max(1.5,scene.seconds-1)},ease:'sine.inOut'}},{start+.2});")
        if art and 'media device' in art:
            animations.append(f"tl.fromTo('{prefix} .media.device',{{rotationY:-14,rotationX:4,transformPerspective:2200}},{{rotationY:-5,rotationX:1,transformPerspective:2200,duration:{scene.seconds+hold},ease:'sine.out'}},{start});")
        for j,c in enumerate(scene.callouts):
            at=start+min(c.at,max(0,scene.seconds-1.2))
            animations.append(f"tl.fromTo('{prefix} .callout[data-callout=\"{j}\"]',{{opacity:0,scale:.5}},{{opacity:1,scale:1,duration:.5,ease:'back.out(2)'}},{at});")
            animations.append(f"tl.fromTo('{prefix} .callout[data-callout=\"{j}\"] .cring',{{scale:.7}},{{scale:1.2,duration:.8,repeat:3,yoyo:true,ease:'sine.inOut'}},{at});")
        if scene.layout=='demo' and scene.demo:
            d=scene.demo
            animations.append(f"tl.fromTo('{prefix} .app',{{opacity:0,y:34,rotationY:-10,transformPerspective:2200}},{{opacity:1,y:0,rotationY:-4,transformPerspective:2200,duration:1,ease:'power3.out'}},{start+.15});")
            animations.append(f"tl.to('{prefix} .app',{{rotationY:-1,transformPerspective:2200,duration:{max(1,scene.seconds+hold-1.15)},ease:'sine.out'}},{start+1.15});")
            if d.kind=='chat':
                n=max(1,len(d.prompt));typing=min(1.8,.06*n)
                animations.append(f"tl.fromTo('{prefix} .ch',{{opacity:0}},{{opacity:1,duration:.02,stagger:{typing/n:.4f}}},{start+1});")
                animations.append(f"tl.fromTo('{prefix} .caret',{{opacity:1}},{{opacity:0,duration:.35,repeat:{int((typing+.8)/.35)},yoyo:true}},{start+1});tl.set('{prefix} .caret',{{opacity:0}},{start+1+typing+.8});")
                animations.append(f"tl.fromTo('{prefix} .bubble.ai',{{opacity:0,y:16}},{{opacity:1,y:0,duration:.6,ease:'power3.out'}},{start+1+typing+.9});")
                animations.append(f"tl.fromTo('{prefix} .card',{{opacity:0,y:28}},{{opacity:1,y:0,duration:.7,ease:'back.out(1.4)'}},{start+1+typing+1.8});")
                animations.append(f"tl.fromTo('{prefix} .chip',{{opacity:0,scale:.6}},{{opacity:1,scale:1,duration:.4,ease:'back.out(2)'}},{start+1+typing+2.5});")
            else:
                animations.append(f"tl.fromTo('{prefix} .greet',{{opacity:0,y:14}},{{opacity:1,y:0,duration:.6}},{start+.9});")
                animations.append(f"tl.fromTo('{prefix} .tile',{{opacity:0,y:22}},{{opacity:1,y:0,duration:.6,ease:'power3.out',stagger:.16}},{start+1.2});")
                for j,t in enumerate(d.tiles):
                    m=re.fullmatch(r'([^\d]*)([\d,]+)([^\d]*)',t.value)
                    if m and m.group(2).replace(',',''):
                        num=int(m.group(2).replace(',',''));pre=escape(m.group(1));suf=escape(m.group(3))
                        animations.append(f"const t{i}_{j}={{v:0}};tl.to(t{i}_{j},{{v:{num},duration:1.4,ease:'power3.out',onUpdate:()=>{{document.querySelectorAll('{prefix} .tile .tv')[{j}].textContent='{pre}'+Math.round(t{i}_{j}.v).toLocaleString('en-US')+'{suf}'}}}},{start+1.3+.16*j});")
                animations.append(f"tl.fromTo('{prefix} .act',{{opacity:0,y:12}},{{opacity:1,y:0,duration:.45,stagger:.1}},{start+2.4});")
        if points and moving:animations.append(f"tl.fromTo('{prefix} .point',{{opacity:0,x:-28}},{{opacity:1,x:0,duration:.6,ease:'power3.out',stagger:.16}},{start+.9});")
        if scene.layout=='stat':
            animations.append(f"const c{i}={{v:0}};tl.to(c{i},{{v:{scene.statistic},duration:1.8,ease:'power3.out',onUpdate:()=>{{document.querySelector('#counter-{i}').textContent=Math.round(c{i}.v).toLocaleString('en-US')}}}},{start+.35});")
            if moving:animations.append(f"tl.fromTo('{prefix} .statistic',{{opacity:0,scale:.9}},{{opacity:1,scale:1,duration:.7,ease:'back.out(1.4)'}},{start+.3});")
        if last:animations.append(f"tl.to('{prefix} .copy',{{opacity:0,y:-10,duration:.45,ease:'power2.in'}},{total-.5});")
        voice=voices.get(scene.id)
        if voice:
            audio.append(f'<audio id="voice-{i}" src="{escape(voice["path"])}" data-start="{start+.25}" data-duration="{voice["duration"]}" data-volume=".9"></audio>')
        if spec.captions and scene.narration and voice:
            for j,(chunk,at,dur) in enumerate(caption_phrases(scene,voice,start)):
                parts.append(f'<div id="caption-{i}-{j}" class="clip caption" data-start="{at:.2f}" data-duration="{dur:.2f}" data-track-index="20"><span>{escape(chunk)}</span></div>')
    if music:
        audio.append(f'<audio id="music" src="{escape(music["path"])}" data-start="0" data-duration="{min(total,music["duration"])}" data-volume="{music.get("volume",1)}"></audio>')
    elif spec.music_asset_id:
        item=media[str(spec.music_asset_id)];duration=min(total,item.get('duration_seconds') or total)
        audio.append(f'<audio id="music" src="{escape(item["path"])}" data-start="0" data-duration="{duration}" data-volume=".12"></audio>')
    parts.append('<div class="grain" data-layout-ignore></div><div class="progress"></div>')
    animations.append(f"tl.fromTo('.progress',{{scaleX:0}},{{scaleX:1,duration:{total},ease:'none'}},0);")
    html=f'''<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><title>{escape(spec.title)}</title><script src="assets/gsap.min.js"></script><style>{css}</style></head><body><div id="root" data-composition-id="main" data-start="0" data-duration="{total}" data-width="{w}" data-height="{h}">{''.join(parts)}{''.join(audio)}</div><script>window.__timelines=window.__timelines||{{}};const tl=gsap.timeline({{paused:true}});{''.join(animations)}window.__timelines.main=tl;</script></body></html>'''
    (folder/'index.html').write_text(html,encoding='utf-8')
    (folder/'hyperframes.json').write_text(json.dumps({'authoringSkill':'general-video'}))
    return total
