const { PGlite } = await import(process.env.PGLITE_MODULE || '../output/marketing-qa/node_modules/@electric-sql/pglite/dist/index.js');
import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const db = new PGlite();
await db.exec(`CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role BYPASSRLS;
CREATE TABLE platform_marketing_campaigns(id uuid primary key);
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO service_role;`);
const sql = name => readFile(new URL('../supabase/'+name,import.meta.url),'utf8');
await db.exec(await sql('APPLY-2026-08-19-dev-bridge.sql'));
await db.exec('ALTER TABLE dev_tasks ADD COLUMN authority_record jsonb');
await db.exec(await sql('APPLY-2026-09-24-dev-desk-agents.sql'));
const migration = await sql('APPLY-2026-09-26-chief-local-work.sql');
await db.exec(migration); await db.exec(migration);
const id='10000000-0000-4000-8000-000000000001',owner='10000000-0000-4000-8000-000000000002',device='10000000-0000-4000-8000-000000000003';
const work={id,owner_id:owner,request_hash:'hash',purpose:'conversation'};
const task={agent:'codex',repo:'frontend',title:'Draft',details:'Build',report_key:'initial',authority_record:{scope:{account_mode:'subscription'}}};
await db.exec('SET ROLE service_role');
for(let i=0;i<2;i++) await db.query('SELECT chief_work_create($1,$2)',[work,task]);
assert.equal((await db.query('SELECT count(*)::int n FROM dev_tasks')).rows[0].n,1);
await assert.rejects(db.query('SELECT chief_work_create($1,$2)',[{...work,request_hash:'changed'},task]));
await db.query(`INSERT INTO dev_bridge_devices(id,name,token_hash,agents) VALUES($1,'Desktop','hash',ARRAY['codex'])`,[device]);
const claim=()=>db.query('SELECT chief_work_claim($1,$2) claimed',[id,device]);
assert.equal((await claim()).rows[0].claimed,false,'old desktop cannot claim subscription work');
await db.query(`UPDATE dev_bridge_devices SET agents=ARRAY['codex','claude','workbench-v1'] WHERE id=$1`,[device]);
assert.equal((await claim()).rows[0].claimed,true);
assert.equal((await claim()).rows[0].claimed,false,'a second claim must not launch twice');
const note={id:owner,from:'kevin',text:'Continue',at:'2026-09-26T12:00:00Z'};
await db.query(`UPDATE dev_tasks SET status='done' WHERE id=$1`,[id]);
for(let i=0;i<2;i++) await db.query('SELECT chief_work_note($1,$2,true)',[id,note]);
let saved=(await db.query('SELECT * FROM dev_tasks')).rows[0];
assert.equal(saved.status,'queued'); assert.equal(saved.notes.length,1); assert.notEqual(saved.report_key,'initial');
assert.equal((await claim()).rows[0].claimed,true,'a reply can launch a new turn');
await db.query('SELECT chief_work_ack($1,$2)',[id,[note.at]]);
await db.query('SELECT chief_work_note($1,$2,false)',[id,{id:device,from:'dev',text:'Result',at:'later'}]);
saved=(await db.query('SELECT * FROM dev_tasks')).rows[0];
assert.ok(saved.notes[0].delivered_at); assert.equal(saved.notes.length,2);
await db.exec('RESET ROLE');
for(const role of ['anon','authenticated']) {
  await db.exec(`SET ROLE ${role}`);
  await assert.rejects(db.query('SELECT * FROM platform_chief_work'));
  await assert.rejects(db.query('SELECT chief_work_claim($1,$2)',[id,device]));
  await assert.rejects(db.query('SELECT chief_work_create($1,$2)',[work,task]));
  await assert.rejects(db.query('SELECT chief_work_note($1,$2,true)',[id,note]));
  await db.exec('RESET ROLE');
}
await db.close(); console.log('Chief work SQL passed: migration replay, service-only access, atomic claims, idempotent requests/replies and report key rotation.');
