import { PGlite } from '../output/marketing-qa/node_modules/@electric-sql/pglite/dist/index.js';
import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const db = new PGlite();
await db.exec(`CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role BYPASSRLS;
CREATE SCHEMA storage; CREATE TABLE storage.buckets(id text PRIMARY KEY,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);`);
const sql = await readFile(new URL('../supabase/APPLY-2026-09-15-platform-marketing.sql',import.meta.url),'utf8');
await db.exec(sql); await db.exec(sql);
const actor='10000000-0000-4000-8000-000000000001';
const a='20000000-0000-4000-8000-000000000001', b='20000000-0000-4000-8000-000000000002';
for(const id of [a,b]) await db.query(`INSERT INTO platform_marketing_posts(id,campaign,payload,content_hash,run_at,expires_at)
VALUES($1,'test','{}','hash',now()+interval '1 hour',now()+interval '2 hours')`,[id]);
await assert.rejects(db.query(`SELECT platform_marketing_approve($1,$2)`,[JSON.stringify([{id:a,revision:1,content_hash:'hash'},{id:b,revision:2,content_hash:'hash'}]),actor]));
assert.deepEqual((await db.query('SELECT status FROM platform_marketing_posts')).rows.map(r=>r.status),['draft','draft']);
const batch=[{id:a,revision:1,content_hash:'hash'},{id:b,revision:1,content_hash:'hash'}];
await db.query('SELECT platform_marketing_approve($1,$2)',[JSON.stringify(batch),actor]);
await assert.rejects(db.query('SELECT platform_marketing_approve($1,$2)',[JSON.stringify(batch),actor]));
await db.exec(`UPDATE platform_marketing_posts SET run_at=now()-interval '1 minute'`);
assert.equal((await db.query('SELECT * FROM platform_marketing_claim()')).rows.length,0);
await db.exec('UPDATE platform_marketing_config SET paused=false');
const claims=await Promise.all([db.query('SELECT * FROM platform_marketing_claim()'),db.query('SELECT * FROM platform_marketing_claim()'),db.query('SELECT * FROM platform_marketing_claim()')]);
assert.equal(new Set(claims.flatMap(r=>r.rows).map(r=>r.id)).size,2);
assert.equal(claims.flatMap(r=>r.rows).length,2);
await db.exec(`UPDATE platform_marketing_posts SET claimed_at=now()-interval '10 minutes' WHERE id='${a}'`);
assert.equal((await db.query('SELECT * FROM platform_marketing_claim()')).rows.length,0);
assert.equal((await db.query('SELECT status FROM platform_marketing_posts WHERE id=$1',[a])).rows[0].status,'uncertain');
await db.exec(`UPDATE platform_marketing_posts SET status='approved',expires_at=now()-interval '30 seconds',run_at=now()-interval '2 minutes' WHERE id='${b}'`);
await db.query('SELECT * FROM platform_marketing_claim()');
assert.equal((await db.query('SELECT status FROM platform_marketing_posts WHERE id=$1',[b])).rows[0].status,'failed');
assert.ok((await db.query('SELECT count(*)::int AS n FROM platform_marketing_events')).rows[0].n>=8);
await db.exec('SET ROLE service_role');
await db.query(`INSERT INTO platform_marketing_posts(id,campaign,payload,content_hash,run_at,expires_at)
VALUES('30000000-0000-4000-8000-000000000001','service-role','{}','hash',now()+interval '1 hour',now()+interval '2 hours')`);
assert.ok((await db.query('SELECT count(*)::int AS n FROM platform_marketing_events')).rows[0].n>=9);
await db.exec('RESET ROLE');
await db.exec('SET ROLE authenticated');
await assert.rejects(db.query('SELECT * FROM platform_marketing_posts'));
await assert.rejects(db.query('SELECT * FROM platform_marketing_claim()'));
await assert.rejects(db.query('SELECT platform_marketing_approve($1,$2)',[JSON.stringify(batch),actor]));
await db.exec('RESET ROLE');
console.log('Database checks passed: replay-safe migration, atomic review, stale versions, pause, unique claims, uncertain recovery, expiry, audit and tenant denial.');
await db.close();
