import { chromium } from '../output/marketing-qa/node_modules/@playwright/test/index.mjs';
import assert from 'node:assert/strict';
const browser=await chromium.launch({headless:true,channel:'msedge'});
const page=await browser.newPage({viewport:{width:1280,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:5293/tests/platform-marketing-preview.html',{waitUntil:'domcontentloaded',timeout:60000});
await page.getByText('Publishing paused',{exact:true}).waitFor();
await page.screenshot({path:'output/marketing-desktop.png',fullPage:true});
await page.getByRole('button',{name:'Select drafts',exact:true}).click();
await page.getByRole('button',{name:'Review selected (2)'}).click();
await page.getByRole('heading',{name:'Approve 2 exact posts'}).waitFor();
assert.equal(await page.getByRole('dialog').getByText('https://mysolutionist.app/',{exact:false}).count(),2);
await page.getByRole('button',{name:'Approve these posts',exact:true}).click();
await page.getByText('Posts approved. Check the publishing status above to confirm delivery is enabled.',{exact:true}).waitFor();
const review=await page.evaluate(()=>window.marketingTest.calls.find(c=>c.path==='/approve'));
assert.equal(review.body.items.length,2);assert.equal(review.body.items[0].revision,1);
await page.getByLabel('Campaign',{exact:true}).fill('new-draft');
await page.getByLabel('Destination account').selectOption('channel-1');
await page.getByLabel('Caption',{exact:true}).fill('A new reviewed message.');
await page.getByRole('button',{name:'Save draft',exact:true}).click();
await page.getByText('Draft saved for review.',{exact:true}).waitFor();
await page.getByRole('button',{name:'Resume approved posts',exact:true}).click();
await page.getByText('Ready — server delivery switch is off',{exact:true}).waitFor();
await page.getByRole('button',{name:'Pause future posts',exact:true}).click();
await page.getByText('Publishing paused',{exact:true}).waitFor();
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:'output/marketing-mobile.png',fullPage:true});
assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
assert.deepEqual(errors,[]);
console.log('Browser checks passed: load, exact batch review, approve, save, resume/pause, desktop and mobile layout.');
await browser.close();
